### PR TITLE
Implemented Hotel Review Sentiment Pre-Built Model [resolves #257]

### LINKED ISSUE #257: Implement Hotel Review Sentiment Pre-Built Model
I implemented the Hotel Review dataset in #254 now I will work on prebuilt model. The dataset is split into 2 in paper, thus, there is a small train size(5800). I require permission to work on small data and compare performance with paper.

### PR DESCRIPTION
**Pull request by onatyap**
- A pre-built model for Hotel Review Sentiment was implemented in `sadedegel/prebuilt/hotel_sentiment.py`.
- `sadedegel/prebuilt/README.md` was updated with explanation on loading and using model.
- Benchmark results on the dataset were added to README.
- Pre-built model with 86% accuracy on holdout test set was saved to `sadedegel/prebuilt/model/` as `hotel_sentiment_classification.joblib`

### CODE REVIEW

**Comment by dafajon** [comment]
Can you please implement tests for the model before we merge.

**Comment by dafajon** [comment]
Also don't forget `~/.sadedegel_data/hotel_sentiment` in `hote_sentiment` dataset tests. Users without the dataset will experience fails.

**Comment by husnusensoy** [comment]
Can you explain results in SVM you compare ?

**Comment by onatyap** [comment]
I updated the comparison part in README using the values from the [paper](https://humir.cs.hacettepe.edu.tr/file/ucan2016.pdf) that first proposed [HUMIR dataset](http://humirapps.cs.hacettepe.edu.tr/tsad.aspx). I think it is more clear now.

**Review by dafajon — APPROVED** [review]
Good work. Maybe add a couple sentences for `ML` and `Hybrid` explanation that are in the papers. Will act as a small abstract for the readers and they will know what those mean.

**Comment by dafajon** [comment]
Updated the branch with latest develop. All checks are passed. Model evaluation outputs the reported score of the metric. Merging and closing.

**Pull request merged**
