### PR TITLE
Implement Pre-Built Movie Review Sentiment Classifier [resolves #218]

### LINKED ISSUE #218: Movie Review Sentiment Prebuilt Model
For the purpose of adding different use cases of our prebuilt function we could implement a movie review sentiment analysis model. There is a decent dataset [available here](https://www.kaggle.com/mustfkeskin/turkish-movie-sentiment-analysis-dataset)  over 80k samples.

For this, these steps going be taken:

- Prepare the dataset,
- Built and test model accuracy,
- Publish the prebuilt model,

### PR DESCRIPTION
**Pull request by ertugrul-dmr**
`sadedegel/prebuilt/README.md`:
- Added how to use prebuilt pipeline
- Added cv score
- Added test set score

`sadedegel/prebuilt/model/movie_sentiment.joblib`:
- Dumped pretrained model weights

`sadedegel/prebuilt/movie_reviews.py`:
- Added cv, build, load and evaluate functions
- Model and vectorizer parameters selected using optimizer with 3 fold results.

`tests/prebuilt/context.py`:
- Added import line for the base model

`tests/prebuilt/test_movie_review_sentiment.py`:
- Added assertions for testing purposes.

### CODE REVIEW

**Comment by ertugrul-dmr** [comment]
I sent the training and test datasets to @dafajon today. Code should be ready to pull when data is added.

**Comment by husnusensoy** [comment]
can you reimplement the model using icu tokenizer.

**Comment by ertugrul-dmr** [comment]
Thanks for updating me, I'm already on it.

One question though, what would be the limit for small dataset? You have any number in your mind?

**Comment by husnusensoy** [comment]
Of course no I dont :) But for majority of the problems ~30K training instance can be used for training without mini batch. Please do check
* Profanity (pipeline)
* Sentiment (pipeline)
* News Categorizer (onelinepipeline)

**Comment by husnusensoy** [comment]
@ertugrul-dmr waiting for your prebuilt model confirming  `sadedegel/prebuilt/CONTRIBUTING.md`  conventions

**Pull request merged**
