### PR TITLE
Implement Pre-Built Customer Reviews Classifier Model [resolves #232]

### LINKED ISSUE #232: Customer Reviews Classification Prebuilt Model
For the purpose of adding different use cases of our prebuilt function we could implement a customer review classification model. There is a decent dataset available [here](https://www.kaggle.com/savasy/multiclass-classification-data-for-turkish-tc32):

- It contians 430K lines, 32 categories
- Each category roughly has 13K comments
- Data is collected from Turkish web sites
- The data contains the comments of the products and product categories

For this, these steps going be taken:

- Prepare the dataset,
- Built and test model accuracy,
- Publish the prebuilt model,

### PR DESCRIPTION
**Pull request by ertugrul-dmr**
`sadedegel/prebuilt/README.md:`

- Added how to use prebuilt pipeline
- Added how to use evaluation
- Added holdout test set f-1 macro score

`sadedegel/prebuilt/model/customer_review_classification.joblib:`

- Dumped pretrained/optimized model weights

`sadedegel/prebuilt/customer_reviews_classification.py:`

- Updated functions according to CONTRIBUTING.md
- Added, build, load and evaluate functions
- Added option to check roc_auc score for predict_proba method
- Model and vectorizer parameters are selected using optimizer with 3 fold results for 50 combinations

`tests/prebuilt/context.py:`

- Added import line for the base model

`tests/prebuilt/test_movie_review_sentiment.py:`

- Added assertions for testing purposes.

### To-do:

- Going to update data paths for sadedegel dataset imports when they're available. (Self note, clean the reminder comments after that)

### CODE REVIEW

**Comment by husnusensoy** [comment]
Where is the dataset ?

**Comment by ertugrul-dmr** [comment]
I sent it to @dafajon, I will be implementing imports accordingly when it's up

**Comment by dafajon** [comment]
import as `customer_review_classification`. I implemented with this name.

**Comment by husnusensoy** [comment]
Do we have any baseline score to compare our model(s) that we can cite in README ?

**Comment by ertugrul-dmr** [comment]
The page I got the dataset from claims 84% F-1 score here:
https://www.kaggle.com/savasy/multiclass-classification-data-for-turkish-tc32

**Comment by husnusensoy** [comment]
document it as we did in other models. Properly site it and resend you PR

**Pull request merged**
