### PR TITLE
Add sbd inspired helper methods.

### PR DESCRIPTION
**Pull request by dafajon**
* Training CLI and SupervisedSummarizer object will need to use model initalization, saving and loading.
* Model initialization is based on `model_type` parameter. SupervisedSummarizer object will have this as an attribute.
* When new models come they will be added to `spv.py` as `get_<model_type>` method.
* There will be no need for additions to class constructor. It will wrap all supervised models.

### CODE REVIEW

**Comment by husnusensoy** [comment]
1. We need a cv based accuracy metric (small corpus as you know) to rank model among other unsupervised models.
2. Ensure that your pickle files are included into `.gitattribute` to be checked out into git lfs.

**Comment by husnusensoy** [comment]
- [ ] Since the model is a supervised one we need a cv based evaluation over ndcg

**Comment by husnusensoy** [comment]
Can we have an update on this ? Or we require to close the pull request ?

**Comment by dafajon** [comment]
I will be providing updates on this and my other issue tasks this week.

**Comment by husnusensoy** [comment]
@dafajon another issue on you.

**Comment by dafajon** [comment]
Rework this PR as Ranker Summarizer.

**Pull request closed without merging**
