### PR TITLE
Feature/tok vocabulary; Support for any word tokenizer

### PR DESCRIPTION
**Pull request by askarbozcan**
Added ability to build vocabulary with and use any word tokenizer (so far only Bert and Simple tokenizers exist).

However, as I have really spotty connection I cannot download the extended raw corpus. I tested the code on a small toy corpus I've created and it seems to work. Can somebody test this branch by building both vocabularies (bert and simple) and running tests using extended corpus?

### CODE REVIEW

**Comment by dafajon** [comment]
I am taking over this PR to build vocabs with extended corpus and complete tests.

**Comment by askarbozcan** [comment]
Merged with updated develop branch.
However bert and simple vocabs need to be built and tests be ran, as tests fail without them.

**Comment by dafajon** [comment]
Now that merge conflicts are resolved I will continue to handle rest. Let's be vigilant to updates on develop so that when our PRs are ready for review there will be no merge conflicts and/or our fixes are not over-riden.

**Comment by dafajon** [comment]
Can you please merge latest changes of 15.2.1. I don't want to override/delete your code changes while fixing merge conflict.

**Comment by askarbozcan** [comment]
Vocabulary changed quite significantly in 0.15.2.1, it would be better to close this PR and create a new one.
Most of the code in this PR is obsolete.

**Comment by dafajon** [comment]
Very well. Let's create and together wrap up a new one ASAP.

**Pull request closed without merging**
