### PR TITLE
Implement Product Review Sentiment Pre-Built Model [resolves #221]

### LINKED ISSUE #221: Implement Product Review Sentiment Pre-Built Model
I will implement the prebuilt model of product review sentiment based on the data set that will resolve issue #219.

### PR DESCRIPTION
**Pull request by irmakyucel**
- Implement hyperparameter optimization.
- Use optimized parameters in final model `build` and `cv` methods.
- Use `fit` instead of `partial_fit` because PassiveAgressiveClassifier did not work well with partial fit. 
- Update README for 3-fold and 5-fold cross validation scores.
- Add a test case for load and prediction of product review sentiment prebuilt model.

### CODE REVIEW

**Comment by husnusensoy** [comment]
can you reimplement the model using icu tokenizer.

**Comment by husnusensoy** [comment]
Score is too low. Please try to find root cause and use a classifier with `predict_proba` function

**Comment by husnusensoy** [comment]
@irmakyucel please do ensure that 

1. you send your pull request to `develop` branch 
2. You sync your ( by merge ) feature branch with development branch first and resolve conflicts.
3. @dafajon kindly requesting your support.

**Comment by dafajon** [comment]
This PR is re-implemented with #238 closing it.

**Pull request closed without merging**
