### PR TITLE
Test Cases for Tokenizer Handlers [resolves #273]

### LINKED ISSUE #273: Hashtag, Emoji and Mention Handler not Working
While working on some preprocessing steps (#270) we noticed that arguments for tokenizers (including Text2Doc) has no effect on the outcome. Basically enable/disable options are not working.

**For this issue we might need to create test cases and find the root cause of the problem.**

To replicate this you can basically follow these steps:

```python
from sadedegel.bblock.word_tokenizer import ICUTokenizer
tokenizer = ICUTokenizer(hashtag=True, mention=True, emoji=True)
text = 'bu #bir @metindir, 🍰'
print(tokenizer._tokenize(text))
```
Will result same with False or True options. Same goes for Text2Doc example below:

```python
from sadedegel.extension.sklearn import Text2Doc
tokenizer = Text2Doc(hashtag=True, mention=True, emoji=True)
texts =[ 'bu', '#bir', '@metindir', '🍰']
print(tokenizer.transform(texts))
```

### PR DESCRIPTION
**Pull request by ertugrul-dmr**
### Files changed:
`tests/test_tokenizer_flags.py:`

- Added 'mention' flag to check handlers for three tokenizers (ICU, Simple, BERT)
- Added 'emoji' flag to check handlers for three tokenizers (ICU, Simple, BERT)
- Added 'hashtag' flag to check handlers for three tokenizers (ICU, Simple, BERT)

### To-do:

Going to add test cases for Text2Doc with @onatyap and enrich test cases for different options.

### CODE REVIEW

**Comment by husnusensoy** [comment]
Great Catch !!!

**Comment by husnusensoy** [comment]
You are calling a private function (`_tokenize`) which you shouldn't when you use `WordTokenizer` class (or subclass) as an user because it is there for internal usage (you can of course can use when you understand the consequences) What you need is 

```python
it = toker(mention=True)
tokens_pred = it(text) # calling __call__ function on WordTokenizer class
```

**Comment by husnusensoy** [comment]
Please do check my commit :) I have already done.

**Comment by ertugrul-dmr** [comment]
Yeah, thank you for update. What I did was just little fixes where I missed in the first place :)

**Comment by husnusensoy** [comment]
can you ensure that Text2Doc also works properly with the exception rules and close the pull request if it is not required.

**Comment by ertugrul-dmr** [comment]
Self note: Going to fix issue with Text2Doc where it's not updating hashtag, mention etc. after first call; then will add test cases. Both steps under this PR.

**Pull request closed without merging**
